sudo: required

# language: none <- no language, please, but this is not possible, so it takes Ruby.

services:
 - docker

env:
 - DOCKER_TAG=debian-stretch-compilers CXX_STANDARD=11 CC=gcc-6 CXX=g++-6
 - DOCKER_TAG=debian-stretch-compilers CXX_STANDARD=11 CC=clang-3.9 CXX=clang++-3.9

script:
 - util/build-in-container.sh ${CXX_STANDARD} banditcpp/build-environments:${DOCKER_TAG}
